version: '3.5'
services:
  hypothesis:
    ports:
      - "5000:5000"
    networks:
      - hypothesis
    environment:
      - APP_URL=http://localhost:5000
      - BROKER_URL=amqp://guest:guest@rabbit:5672//
      - SECRET_KEY=notverysecretafterall
      - DATABASE_URL=postgresql://postgres@postgres/postgres
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - ELASTICSEARCH_INDEX=hypothesis
      - AUTHORITY=localhost
  postgres:
    image: postgres:9.4-alpine
    networks:
      - hypothesis
  elasticsearch:
    image: nickstenning/elasticsearch-icu
    networks:
      - hypothesis
  rabbit:
    image: rabbitmq:3.6-management-alpine
    networks:
      - hypothesis
networks:
  hypothesis:
