version: '3.5'
services:
  server:
    image: "openstax/hypothesis-server:dev"
    ports:
      - "5000:5000"
    networks:
      - hypothesis
      - openstax
    environment:
      - APP_URL=https://hypothesis.sandbox.openstax.org
      - BROKER_URL=amqp://guest:guest@rabbit:5672//
      - SECRET_KEY=notverysecretafterall
      - DATABASE_URL=postgresql://postgres@postgres94/postgres
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - ELASTICSEARCH_INDEX=hypothesis
      - AUTHORITY=localhost
      - CLIENT_ID=nosuchid
      - CLIENT_SECRET=nosuchsecret
  rabbit:
    image: rabbitmq:3.6-management-alpine
    networks:
      - hypothesis
networks:
  hypothesis:
  openstax:
    external:
      name: openstax
